{"level":"info","memory_mb":14.383644104003906,"message":"Phase started: Edge Processing","phase":"Edge Processing","timestamp":154}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":72000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 48)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":6856}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":3000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 2)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":6862}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":27000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 18)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":6901}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":28500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 19)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":6916}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":7500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 5)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":6948}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":21000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 14)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":7001}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":16500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 11)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":7004}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":12000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 8)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":7024}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":10500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 7)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":7262}
{"current":61500,"eta_seconds":"135","level":"info","memory_mb":99.11982727050781,"message":"Progress: Edge Processing","percentage":"9.46%","rate_per_second":"4366.04","timestamp":"2025-08-24T19:25:46.074Z","total":650000}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":108000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 22)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20543}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":102000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 18)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20625}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":120000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 30)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20626}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":103500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 19)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20668}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":96000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 14)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20736}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":99000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 16)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20738}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":100500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 17)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20747}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":97500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 15)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20748}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":81000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 4)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20867}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":118500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 29)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20896}
{"current":121500,"eta_seconds":"140","level":"info","memory_mb":63.87559509277344,"message":"Progress: Edge Processing","percentage":"18.69%","rate_per_second":"3786.34","timestamp":"2025-08-24T19:26:04.077Z","total":650000}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":220500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 47)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38475}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":211500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 41)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38583}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":214500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 43)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38600}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":207000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 38)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38676}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":216000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 44)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38677}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":223500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 49)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38739}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":219000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 46)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38740}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":210000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 40)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38741}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":217500},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 45)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38861}
{"context":{"axios":{"code":"ETIMEDOUT","url":"/"},"limit":1500,"message":"","offset":213000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 42)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":38893}
{"current":181500,"eta_seconds":"152","level":"info","memory_mb":39.074981689453125,"message":"Progress: Edge Processing","percentage":"27.92%","rate_per_second":"3089.99","timestamp":"2025-08-24T19:26:30.726Z","total":650000}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":273000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 32)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":68763}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":267000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 28)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":69570}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":243000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 12)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":69631}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":244500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 13)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":69809}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Temporarily Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":277500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 35)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":70686}
{"current":249000,"eta_seconds":"114","level":"info","memory_mb":63.27528381347656,"message":"Progress: Edge Processing","percentage":"38.31%","rate_per_second":"3522.62","timestamp":"2025-08-24T19:26:42.674Z","total":650000}
{"current":324000,"eta_seconds":"79","level":"info","memory_mb":78.51643371582031,"message":"Progress: Edge Processing","percentage":"49.85%","rate_per_second":"4142.69","timestamp":"2025-08-24T19:26:50.198Z","total":650000}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":418500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 29)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":89725}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":444000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 46)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":90102}
{"current":396000,"eta_seconds":"58","level":"info","memory_mb":75.12712860107422,"message":"Progress: Edge Processing","percentage":"60.92%","rate_per_second":"4394.97","timestamp":"2025-08-24T19:27:02.091Z","total":650000}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":504000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 36)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":99097}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":450000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 0)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":99387}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":505500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 37)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":101044}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":516000},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 44)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":101342}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":475500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 17)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":102543}
{"current":463500,"eta_seconds":"42","level":"info","memory_mb":44.365997314453125,"message":"Progress: Edge Processing","percentage":"71.31%","rate_per_second":"4486.06","timestamp":"2025-08-24T19:27:15.308Z","total":650000}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":577500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 35)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":113625}
{"current":537000,"eta_seconds":"24","level":"info","memory_mb":41.75209045410156,"message":"Progress: Edge Processing","percentage":"82.62%","rate_per_second":"4687.99","timestamp":"2025-08-24T19:27:26.536Z","total":650000}
{"context":{"axios":{"code":"ERR_BAD_RESPONSE","status":503,"statusText":"Service Unavailable","url":"/"},"limit":1500,"message":"Request failed with status code 503","offset":616500},"level":"error","message":"Error occurred Request failed with status code 503","stack":"AxiosError: Request failed with status code 503\n    at settle (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.postWithRetry (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:156:15)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:120:24)\n    at async Promise.all (index 11)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:83:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":124014}
{"current":585500,"eta_seconds":"14","level":"info","memory_mb":64.45343780517578,"message":"Progress: Edge Processing","percentage":"90.08%","rate_per_second":"4692.90","timestamp":"2025-08-24T19:27:36.751Z","total":650000}
{"duration_ms":124764,"level":"info","memory_mb":64.47158813476562,"message":"Phase completed: Edge Processing","phase":"Edge Processing","records":585500,"timestamp":"2025-08-24T19:27:36.752Z"}
{"cpu_seconds":"55.75","error_count":64500,"level":"info","memory_peak_mb":"160.12","message":"ETL Process Completed","records_per_second":"4692.86","timestamp":"2025-08-24T19:27:36.753Z","total_duration_seconds":"124.76","total_records":585500}
